const express = require('express');
const Project = require('../models/Project');

const router = express.Router();

// Log at module load whether AI API key is present
const aiApiKey = process.env.AI_API_KEY;
if (!aiApiKey) {
  console.error('Environment check: AI_API_KEY is MISSING');
} else {
  console.log('Environment check: AI_API_KEY is present');
}

// Handler for POST requests. This route is mounted in server.js as
// `app.use('/api/onboard', onboardRoutes);` so the frontend should call
// POST /api/onboard — we log incoming requests so the terminal shows activity.
router.post('/', async (req, res) => {
  console.log(`Incoming request: POST ${req.originalUrl}`);

  try {
    const {
      companyName,
      email,
      industry,
      features,
      platform,
      integrations,
      audience,
      aesthetic,
    } = req.body || {};

    // Re-check env var inside the request handler and log if missing.
    const key = process.env.AI_API_KEY;
    if (!key) {
      console.error('Request handling error: AI_API_KEY not configured');
      return res.status(500).json({ error: 'AI API key not configured' });
    }

    // Safely build feature list
    let featureListText = 'No features provided.';
    try {
      if (Array.isArray(features) && features.length) {
        featureListText = features.map((f) => `- ${f}`).join('\n');
      }
    } catch (mapErr) {
      console.error('Error mapping features array:', mapErr);
      featureListText = 'Error reading features list.';
    }

    const blueprint = `# ${companyName || 'Unnamed Company'} - System Architecture Blueprint

## Project Overview
- **Company**: ${companyName || 'N/A'}
- **Contact**: ${email || 'N/A'}
- **Industry**: ${industry || 'N/A'}
- **Target Platform**: ${platform || 'N/A'}
- **Audience**: ${audience || 'N/A'}
- **Aesthetic**: ${aesthetic || 'N/A'}

## Feature Scope
The following features have been selected for this project:
${featureListText}

## Required Integrations
${integrations || 'To be determined during development phase.'}

## Next Steps
1. Review this architecture with your team
2. Schedule technical kickoff meeting
3. Begin sprint planning and resource allocation

---
*Generated by Forge Setup System*
`;

    const project = new Project({
      companyName: companyName || 'Unknown',
      email: email || 'unknown@example.com',
      industry: industry || 'Unknown',
      features: Array.isArray(features) ? features : [],
      platform: platform || 'web',
      audience: audience || '',
      aesthetic: aesthetic || '',
      aiGeneratedBlueprint: blueprint,
      status: 'completed',
    });

    let savedProject;
    try {
      savedProject = await project.save();
      console.log('Project saved with id:', savedProject._id);
    } catch (saveErr) {
      console.error('Database save error:', saveErr);
      // attempt to persist a failed record for troubleshooting
      const fallback = new Project({
        companyName: companyName || 'Unknown',
        email: email || 'unknown@example.com',
        industry: industry || 'Unknown',
        features: Array.isArray(features) ? features : [],
        platform: platform || 'web',
        audience: audience || '',
        aesthetic: aesthetic || '',
        aiGeneratedBlueprint: null,
        status: 'failed',
      });

      try {
        await fallback.save();
        console.log('Saved fallback failed-project record for debugging');
      } catch (fallbackErr) {
        console.error('Error saving fallback project:', fallbackErr);
      }

      return res.status(500).json({ error: 'Database save failed', message: saveErr.message });
    }

    return res.status(201).json({ success: true, project: savedProject });
  } catch (error) {
    console.error('Unhandled error in /api/onboard handler:', error);
    return res.status(500).json({ error: 'Failed to generate project blueprint', message: error.message });
  }
});

module.exports = router;
